// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZIdeq2TWIf3GKzeuXAgvlQEMzx7_M-Q',
    appId: '1:296271131741:web:3358df78994d6d106109b4',
    messagingSenderId: '296271131741',
    projectId: 'unityapp-63516',
    authDomain: 'unityapp-63516.firebaseapp.com',
    storageBucket: 'unityapp-63516.appspot.com',
    measurementId: 'G-5V2BL7FK46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAB3fkHVDb1k83_sTK5kwZHSxFYy4WnQ',
    appId: '1:296271131741:android:8891b1565f2b91566109b4',
    messagingSenderId: '296271131741',
    projectId: 'unityapp-63516',
    storageBucket: 'unityapp-63516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzsUrMdhK3sQIDE6i2W-6WtAH1vbAzjo',
    appId: '1:296271131741:ios:cb8f12fd3bb319726109b4',
    messagingSenderId: '296271131741',
    projectId: 'unityapp-63516',
    storageBucket: 'unityapp-63516.appspot.com',
    iosBundleId: 'com.example.logingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzsUrMdhK3sQIDE6i2W-6WtAH1vbAzjo',
    appId: '1:296271131741:ios:93c77462f42beacc6109b4',
    messagingSenderId: '296271131741',
    projectId: 'unityapp-63516',
    storageBucket: 'unityapp-63516.appspot.com',
    iosBundleId: 'com.example.logingPage.RunnerTests',
  );
}
