// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRFBfqgKyf5cXgGvX6OVPy1I_JByPpfg',
    appId: '1:533485109836:web:933b967e59e62ccfd76ae9',
    messagingSenderId: '533485109836',
    projectId: 'unityaid-dc259',
    authDomain: 'unityaid-dc259.firebaseapp.com',
    storageBucket: 'unityaid-dc259.appspot.com',
    measurementId: 'G-WMC9028F46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7OQ7z2dxKEFBxVOY1vk9CV3K_mXjya4',
    appId: '1:533485109836:android:7ea4a305391a1007d76ae9',
    messagingSenderId: '533485109836',
    projectId: 'unityaid-dc259',
    storageBucket: 'unityaid-dc259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-4MPpuKOWEc0GQnU0_GBndBkUcjUmk0',
    appId: '1:533485109836:ios:fad77858c6c6de41d76ae9',
    messagingSenderId: '533485109836',
    projectId: 'unityaid-dc259',
    storageBucket: 'unityaid-dc259.appspot.com',
    iosBundleId: 'com.example.logingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-4MPpuKOWEc0GQnU0_GBndBkUcjUmk0',
    appId: '1:533485109836:ios:e8dbd353b68e53f8d76ae9',
    messagingSenderId: '533485109836',
    projectId: 'unityaid-dc259',
    storageBucket: 'unityaid-dc259.appspot.com',
    iosBundleId: 'com.example.logingPage.RunnerTests',
  );
}
