// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJcHI4JatQnJ7QVLUt64zIS89NFpStQPI',
    appId: '1:588520593194:web:060f16a47a99a0e1fcb053',
    messagingSenderId: '588520593194',
    projectId: 'unityaid-cfcfd',
    authDomain: 'unityaid-cfcfd.firebaseapp.com',
    storageBucket: 'unityaid-cfcfd.appspot.com',
    measurementId: 'G-W13H17YN2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPdLwXBPrp40XG01YaHiXaHQpUkBgwN0',
    appId: '1:588520593194:android:ea057bd96ce4213dfcb053',
    messagingSenderId: '588520593194',
    projectId: 'unityaid-cfcfd',
    storageBucket: 'unityaid-cfcfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSwEEGlUJOXEmWHmKAs2eQbvFjLaiK7LY',
    appId: '1:588520593194:ios:550e210bd361cff3fcb053',
    messagingSenderId: '588520593194',
    projectId: 'unityaid-cfcfd',
    storageBucket: 'unityaid-cfcfd.appspot.com',
    iosClientId: '588520593194-evkqafenuoja4gug6tf9un8bktdtupe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.logingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSwEEGlUJOXEmWHmKAs2eQbvFjLaiK7LY',
    appId: '1:588520593194:ios:bf242cbeaee19c5bfcb053',
    messagingSenderId: '588520593194',
    projectId: 'unityaid-cfcfd',
    storageBucket: 'unityaid-cfcfd.appspot.com',
    iosClientId: '588520593194-u0oo2p85vpke7rdvg24avs4epqap9nn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.logingPage.RunnerTests',
  );
}
